# Generated by Django 5.2.7 on 2026-03-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='add_my_image_to_magazine',
        ),
        migrations.RemoveField(
            model_name='user',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subject',
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('founding_member', 'Founding Member'), ('committee_leader', 'Committee Leader'), ('general_member', 'General Member'), ('school_member', 'School Member')], max_length=255, null=True),
        ),
    ]
