# Generated by Django 5.2.7 on 2026-03-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_add_my_image_to_magazine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('other', 'Other')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='unit_name',
            field=models.CharField(blank=True, choices=[('cumilla_district', 'Cumilla District'), ('burichang_upazila', 'Burichang Upazila'), ('debidwer_upazila', 'Debidwer Upazila'), ('barura_upazila', 'Barura Upazila'), ('sadar_dakshin_upazila', 'Sadar Dakshin Upazila'), ('brahmanpara_upazila', 'Brahmanpara Upazila'), ('comilla_modern_high_school', 'Comilla Modern High School'), ('comilla_high_school', 'Comilla High School')], max_length=50, null=True),
        ),
    ]
